### ISSUE TITLE
Auto-generate documentation from proto files

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/api-clients#126]
Now that this repo is public, auto-generate documentation from proto files in HTML and Markdown formats.

Use a `buf` config such as:
```yaml
---
version: v1beta1
plugins:
  - name: doc
    out: proto/doc
    opt: html,index.html
    strategy: all
  - name: doc
    out: proto/doc
    opt: markdown,index.md
    strategy: all
```
